name: multiroom
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.6.1+32

environment:
  sdk: ">=3.3.3 <4.0.0"

# dependency_overrides:
#   intl: ^0.19.0

dependencies:
  flutter:
    sdk: flutter

  animated_toggle_switch: ^0.8.2
  another_xlider: ^3.0.2
  async: ^2.11.0
  auto_injector: ^2.0.4
  collection: ^1.18.0
  crypto: ^3.0.3
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  expandable: ^5.0.1
  # external_app_launcher: ^4.0.0
  flutter_expandable_fab: ^2.3.0
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  logger: ^2.3.0
  mask_text_input_formatter: ^2.9.0
  material_design_icons_flutter: ^7.0.7296
  mobile_scanner: ^5.1.1
  network_info_plus: ^5.0.3
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  restart_app: ^1.2.1
  routefly: ^2.0.2
  share_plus: ^10.0.2
  signals: ^5.5.0
  toastification: ^2.0.0
  udp: ^5.0.3
  url_launcher: ^6.3.0
  visibility_detector: ^0.4.0+2
  window_manager: ^0.3.9
  cupertino_icons: ^1.0.3

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/controlArtLogo.png"
  image_path_ios: "assets/images/controlArtLogo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/fundo.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/splash3.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/images/controlArtLogo-.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/images/controlArtLogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/controlArtLogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/controlArtLogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/music_players/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
