name: multiroom
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.7.7+18

environment:
  sdk: ">=3.3.3 <4.0.0"

# dependency_overrides:
#   intl: ^0.19.0

dependencies:
  flutter:
    sdk: flutter

  animated_toggle_switch: ^0.8.2
  auto_injector: ^2.0.4
  collection: ^1.18.0
  crypto: ^3.0.3
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  expandable: ^5.0.1
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  logger: ^2.3.0
  mask_text_input_formatter: ^2.9.0
  material_design_icons_flutter: ^7.0.7296
  mobile_scanner: ^5.1.1
  network_info_plus: ^5.0.3
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  restart_app: ^1.2.1
  routefly: ^2.0.2
  share_plus: ^9.0.0
  signals: ^5.2.2
  toastification: ^2.0.0
  udp: ^5.0.3
  url_launcher: ^6.3.0
  visibility_detector: ^0.4.0+2
  window_manager: ^0.3.9

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
