// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/(modules)/devices/ui/pages/device_demo_page.dart' as a2;
import 'app/(modules)/devices/ui/pages/device_info_page.dart' as a1;
import 'app/(modules)/udp/ui/pages/udp_page.dart' as a0;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/udp/ui/pages/udp',
        uri: Uri.parse('/udp/ui/pages/udp'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.UdpPage(),
        ),
      ),
      RouteEntity(
        key: '/devices/ui/pages/device_info',
        uri: Uri.parse('/devices/ui/pages/device_info'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.DeviceInfoPage(),
        ),
      ),
      RouteEntity(
        key: '/devices/ui/pages/device_demo',
        uri: Uri.parse('/devices/ui/pages/device_demo'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.DeviceDemoPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  udp: (
    path: '/udp',
    ui: (
      path: '/udp/ui',
      pages: (
        path: '/udp/ui/pages',
        udp: '/udp/ui/pages/udp',
      ),
    ),
  ),
  devices: (
    path: '/devices',
    ui: (
      path: '/devices/ui',
      pages: (
        path: '/devices/ui/pages',
        deviceInfo: '/devices/ui/pages/device_info',
        deviceDemo: '/devices/ui/pages/device_demo',
      ),
    ),
  ),
);
