// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/(modules)/configs/pages/configs_page.dart' as a4;
import 'app/(modules)/configs/pages/device_configuration_page.dart' as a3;
import 'app/(modules)/demo/demo_page.dart' as a0;
import 'app/(modules)/home/pages/home_page.dart' as a1;
import 'app/(modules)/scanner/pages/scanner_page.dart' as a6;
import 'app/(modules)/startup/pages/startup_page.dart' as a5;
import 'app/(modules)/udp/ui/pages/udp_page.dart' as a2;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/demo/home',
        uri: Uri.parse('/demo/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.HomePage(),
        ),
      ),
      RouteEntity(
        key: '/home/pages/home',
        uri: Uri.parse('/home/pages/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.HomePage(),
        ),
      ),
      RouteEntity(
        key: '/udp/ui/pages/udp',
        uri: Uri.parse('/udp/ui/pages/udp'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.UdpPage(),
        ),
      ),
      RouteEntity(
        key: '/configs/pages/device_configuration',
        uri: Uri.parse('/configs/pages/device_configuration'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a3.DeviceConfigurationPage(),
        ),
      ),
      RouteEntity(
        key: '/configs/pages/configs',
        uri: Uri.parse('/configs/pages/configs'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a4.ConfigsPage(),
        ),
      ),
      RouteEntity(
        key: '/startup/pages/startup',
        uri: Uri.parse('/startup/pages/startup'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a5.StartupPage(),
        ),
      ),
      RouteEntity(
        key: '/scanner/pages/scanner',
        uri: Uri.parse('/scanner/pages/scanner'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a6.ScannerPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  demo: (
    path: '/demo',
    home: '/demo/home',
  ),
  home: (
    path: '/home',
    pages: (
      path: '/home/pages',
      home: '/home/pages/home',
    ),
  ),
  udp: (
    path: '/udp',
    ui: (
      path: '/udp/ui',
      pages: (
        path: '/udp/ui/pages',
        udp: '/udp/ui/pages/udp',
      ),
    ),
  ),
  configs: (
    path: '/configs',
    pages: (
      path: '/configs/pages',
      deviceConfiguration: '/configs/pages/device_configuration',
      configs: '/configs/pages/configs',
    ),
  ),
  startup: (
    path: '/startup',
    pages: (
      path: '/startup/pages',
      startup: '/startup/pages/startup',
    ),
  ),
  scanner: (
    path: '/scanner',
    pages: (
      path: '/scanner/pages',
      scanner: '/scanner/pages/scanner',
    ),
  ),
);
